### ISSUE TITLE
MATH.dataset_zf

### ISSUE THREAD

**Issue by hedy881028** [Yiwei98/TDG#1]
#### Description
Error: `ModuleNotFoundError: No module named 'MATH'` when executing `finetune.py`.

#### To Reproduce
I tried to reproduce your code. But when I executed `bash run_neg.sh`, it said that `ModuleNotFoundError: No module named 'MATH'`.
I found that the problem was due to `from MATH.dataset_zf import MATHCHATFILEDataset` in `finetune.py`.
However, I couldn't find any file or module named `MATH` in the directory.
Did the file be replaced with `GPT3.5-turbo-MATH` or anything else?

Looking forward to your reply. Thank you.

**Comment by Yiwei98** [comment]
Thank you so much for bringing up the relevant issue! We have added and corrected the related code. If there are any further issues, please feel free to contact us.

**Comment by hedy881028** [comment]
Thank you for the reply!
